# -*- coding: utf-8 -*-
"""Practica2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APzRgUTVudIdt4FeOjaw_oDv__g5tknr
"""

# Respuestas precargadas y retroalimentación
respuestas = {
    "Hola": "¡Hola! ¿Cómo estás?",
    "¿Cómo te llamas?": "Me llamo ChatBot.",
    "¿Que puesto podrias desempeñar?": "Lo siento, no puedo decirte la hora en este momento."
}

# Función para manejar la conversación
def chat():
    print("Bienvenido al ChatBot. Escribe 'Salir' para terminar la conversación.")

    while True:
        # Recibe la entrada del usuario
        user_input = input("Tú: ")

        # Verifica si el usuario quiere salir

        if user_input.lower() == 'salir':
            print("ChatBot: ¡Hasta luego!")
            break

        # Verifica si la entrada del usuario tiene una respuesta predefinida
        if user_input in respuestas:
            respuesta = respuestas[user_input]
            print("ChatBot:", respuesta)
        else:
            # Si no hay una respuesta predefinida, solicita al usuario que proporcione una respuesta
            nueva_respuesta = input("ChatBot: No sé qué decir. ¿Qué debo responder a eso? ")
            respuestas[user_input] = nueva_respuesta
            print("ChatBot: Gracias por la retroalimentación.")

# Inicio del chat
if __name__ == "__main__":
    chat()